### ISSUE TITLE
term.typing results in undefined messages

### ISSUE THREAD

**Issue by davidem** [coolapso/hugo-theme-terminalcv#17] opened 2024-06-13 09:20 UTC
Hi, I see you changed from jquery.terminal 2.35.1 to 2.42.0. 

Unfortunately term.typing results in a massive spam of undefined messages when using the new version.

This is with 2.42.0 set in head.html: 
https://github.com/coolapso/hugo-theme-terminalcv/assets/706591/f3194252-38dd-47be-8500-54a28735a2d3

This is with 2.35.1 set in head.html: 
https://github.com/coolapso/hugo-theme-terminalcv/assets/706591/8b8cbc4c-f648-4140-bf90-5626a0506fb4

I call term.typing like this: 
`term.typing('echo', 5, '{{ .Site.Params.bootsequence9 }}', function() { });`

Bootsequence parameter: 
```
  bootsequence9: |
    [OSBoot1]
    [OSBoot2]
    [OSBoot3]
    [OSBootTheme]

    Boot Complete
```

I assume this is not because of your rework, but I thought to ask first here.

**Comment by coolapso** [comment] 2024-06-13 09:26
At glance it doesn't look related by my changes to the theme, but I can't fully exclude it  ... do you have a fork I can look into?

**Comment by davidem** [comment] 2024-06-13 10:00
yes, here it is: https://github.com/davidem/terminalcv_test

**Comment by coolapso** [comment] 2024-06-13 15:21
What I want to look at is the changes to the theme. The repo you sent is missing the gitm modules configuration. there's no link to a git module

**Comment by davidem** [comment] 2024-06-13 20:46
My bad... please check again 😉

**Comment by davidem** [comment] 2024-06-27 11:08
Have you had a chance to look? :)

**Comment by coolapso** [comment] 2024-06-27 11:11
Hi, I am sorry this has completely slipped through, i'll see if I have time to take a look at it sometime this week or during the weekend.

**Comment by coolapso** [comment] 2024-06-30 11:02
:thinking:  either I am misisng something or I don't see anything wrong .... 


https://github.com/coolapso/hugo-theme-terminalcv/assets/14358086/e8f0d243-ac86-4dcf-9fbf-41f8e66e5041

**Comment by davidem** [comment] 2024-07-01 13:03
v2.35.1 is currently selected, which works. Please switch to 2.42.0 in themes/terminalcv/layouts/partials/head.html: 

<img width="1169" alt="Screenshot 2024-07-01 at 15 01 57" src="https://github.com/coolapso/hugo-theme-terminalcv/assets/706591/e10a0ce7-edf8-4c3b-adf9-650a9e0d0a35">

**Comment by coolapso** [comment] 2024-07-10 21:52
I took a look and could reproduce the issue. however I think this is beyond my skill level with Javascript in general.

**Comment by coolapso** [comment] 2024-07-10 22:07
I took a look and could reproduce the issue. however I think this is beyond my skill level with JavaScript in general. and there's a couple of things that puzzle me .. the first one is why does it work with v2.35 and not with 2.42. 

Then the "undefined" message you see usually pops up when you trying to call a function that does not exist, however the console does not log anything. 

I could isolate the issue and when commenting this part of the code it stops: 

```
            setTimeout(function() {
               term.typing('echo', 5, '{{ .Site.Params.bootsequence9 }}', function() { });
            }, 1);
``` 

I was also able to successfully use the `term.type()` function within the code, eg. replaced the echo from the version command. 
Which makes me even more confused if the issue is (most likely) a consequence of my refactor and my (probably quite shitty) JS code or if there's actually an issue with the jquery terminal and the `term.type()` function. 

I also tried replacing the `term.typing()` with `term.echo("{{ .site.Params.bootsequence9 }}", {typing: true, delay: 5})` and resulted in the same behavior, which makes sense since  the term.echo essentially uses the term.typing behind the scenes. 

I am completely lost with this one and not sure if I can help you much further.

@jcubic sorry to tag you, but since I know sometimes you lurk around, if you have some time could you possibly shed some of your wisdom here? Thanks a lot :)

**Comment by jcubic** [comment] 2024-07-11 08:02
If you have an online demo that shows the issue I can see if I can debug the code and see what is happening. There was a bug with undefined when there was blank line but it was fixed. I think that bug was always there.

**Comment by jcubic** [comment] 2024-07-12 11:20
I just watched the video, and it looks exactly like a bug with blank line during animation.

- https://github.com/jcubic/jquery.terminal/issues/946

if you can create reproduction with latest version, I can check it out. According to my tests, it was fixed. I would assume that the error happen in 2.35.1 and is don't appear in 2.42.0 (not the other way around).

**Comment by jcubic** [comment] 2024-07-12 11:24
I was wrong, the error still appears in low level `term.typing`. I suggest using higher level API:

```javascript
term.echo('{{ .Site.Params.bootsequence9 }}', {
    typing: true,
    delay: 5
});
```

Maybe the bug was not present in `term.typing `and when adding a fix to normal animation, it manifested there.

**Comment by jcubic** [comment] 2024-07-12 11:34
I just checked again my demo, and it seems that the error was not fixed. Only `term.skip()` used to stop the loop was clearing those `undefined`.

**Comment by coolapso** [comment] 2024-07-12 13:57
@jcubic the video does not repredent the actuall error ... I'll try to build @davidem  Branch today and provide you with a video and a code where the issue happens.

**Comment by jcubic** [comment] 2024-07-12 15:33
If the error is only about infinite loop of undefined when there is blank line, it was fixed in version 2.42.2.

**Comment by davidem** [comment] 2024-07-12 18:20
I'm on holiday at the moment but will check when I'm back 😁👌🏻

**Comment by coolapso** [comment] 2024-07-13 08:58
I have pulled @davidem  repository and built the page using v2.42.2 and  can confirm that the issue no longer happens. 
This hugo theme [has been updated](https://github.com/coolapso/hugo-theme-terminalcv/releases/tag/v3.0.1) and is now using it. 

Whatever magic you did worked! thanks a lot @jcubic  :D 

Closing this as it seems to be resolved :)

**Closed as completed by coolapso** 2024-07-13 08:58 UTC
